version: "3"

services:
  weather-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - OPEN_WEATHER_API_KEY=${OPEN_WEATHER_API_KEY}
